### ISSUE TITLE
Cannot run cui2vec-converter.py

### ISSUE THREAD

**Issue by allieonpoppyfield** [leanderme/sytora#1]
Traceback (most recent call last):
  File "C:\asd\sytora\cui2vec-converter.py", line 6, in <module>
    cui_vecs_df = pd.read_csv('./cui2vec_pretrained.csv')
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'./cui2vec_pretrained.csv' does not exist

**Comment by leanderme** [comment]
The last line gives you the answer already, ./cui2vec_pretrained.csv' does not exist. You need to get the pretrained embeddings first, available here: https://figshare.com/s/00d69861786cd0156d81. Place them in the data folder.

**Comment by allieonpoppyfield** [comment]
> The last line gives you the answer already, ./cui2vec_pretrained.csv' does not exist. You need to get the pretrained embeddings first, available here: https://figshare.com/s/00d69861786cd0156d81. Place them in the data folder.

its doesnt work if i place them the "data" folder. but placing them in root folder solved my proplem< thanks
