### ISSUE TITLE
cui2vec-converter.py showing error

### ISSUE THREAD

**Issue by anaymalpani** [leanderme/sytora#4]
Traceback (most recent call last):
  File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CUI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cui2vec-converter.py", line 7, in <module>
    cui_vecs_df.set_index('CUI', inplace=True)
  File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 4178, in set_index
    level = frame[col]._values
  File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CUI'
![error](https://user-images.githubusercontent.com/6376413/58634474-01d21400-8309-11e9-9927-a7443cd211dc.jpg)

**Comment by Pancham97** [comment]
> Traceback (most recent call last):
> File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
> return self._engine.get_loc(key)
> File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'CUI'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "./cui2vec-converter.py", line 7, in 
> cui_vecs_df.set_index('CUI', inplace=True)
> File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 4178, in set_index
> level = frame[col]._values
> File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in **getitem**
> indexer = self.columns.get_loc(key)
> File "/home/adwait/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
> return self._engine.get_loc(self._maybe_cast_indexer(key))
> File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
> File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
> File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'CUI'
> ![error](https://user-images.githubusercontent.com/6376413/58634474-01d21400-8309-11e9-9927-a7443cd211dc.jpg)

This is happening to me too.

**Comment by Pancham97** [comment]
Me too.

**Comment by Pancham97** [comment]
I am facing the same issue. I guess this is because the cui2vec-pretrained.csv` does not have any CUI column name.

**Comment by Pancham97** [comment]
I am facing the same issue. I guess this is because the `cui2vec-pretrained.csv` does not have any CUI column name.

**Comment by gliitterpuke** [comment]
Is there an update on this?

**Comment by leanderme** [comment]
I'm sorry for the late reply! @Pancham97 @anaymalpani  @gliitterpuke could you have a quick look on the `cui2vec-pretrained.csv` file and check the column names? In case there is a typo, I apologize for this. For a quick fix, please rename the column to `CUI`.

**Comment by gliitterpuke** [comment]
@leanderme you're right! CUI was missing as the column name :) renamed and it ran perfectly

**Comment by AlexHodo** [comment]
Which column should I rename to 'CUI'?

**Comment by egealpay** [comment]
> Which column should I rename to 'CUI'?

Can anyone give an answer for this question?
